services:
  postgres_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db  # Specify the database name here as 'db'
    ports:
      - "5432:5432"
    volumes:
      - ./models/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script

  localstack:
    image: localstack/localstack
    restart: always
    ports:
      - "4566:4566"  # LocalStack API port
      - "4510:4510"  # LocalStack S3 port
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./storage:/var/lib/localstack"
      
  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
      - localstack
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres_db/db?sslmode=disable
      - storagetype=local # can change to s3
      - AWS_ENDPOINT_URL=http://localstack:4566
    command: sh -c "sleep 10 && ./main"  # Wait for LocalStack to be ready before starting the app