version: '3.8'

services:
  postgres_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db  # Specify the database name here as 'db'
    ports:
      - "5432:5432"
    volumes:
      - ./models/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script

  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres_db/db?sslmode=disable
